export type TrainingCategory = 'fuerza' | 'tactico' | 'resistencia' | 'pliometria' | 'prevencion';

export type IllustrationType =
  | 'squat' | 'hip_thrust' | 'hip_hinge' | 'plank' | 'bench_press'
  | 'shoulder_press' | 'row' | 'lunge' | 'pushup' | 'mountain_climber'
  | 'nordic_curl' | 'cable_extension' | 'squat_jump' | 'run' | 'sprint'
  | 'jump_vertical' | 'depth_jump' | 'jump_lateral' | 'bounds' | 'skipping'
  | 'hurdle_jump' | 'agility_ladder' | 'triple_jump' | 'balance_single'
  | 'stretch_dynamic' | 'foam_roll' | 'band_walk' | 'hip_mobility'
  | 'foot_activation' | 'warmup_run' | 'ice_bath' | 'copenhagen'
  | 'field_rondo' | 'field_positions' | 'field_2v1' | 'field_transition'
  | 'field_press' | 'field_wide' | 'field_counter' | 'field_corner'
  | 'field_defensive' | 'field_buildup' | 'field_ssg';

export interface Exercise {
  name: string;
  description: string;
  duration: string;
  benefit: string;
  illustration: IllustrationType;
}

export const EXERCISES: Record<TrainingCategory, Exercise[]> = {
  fuerza: [
    {
      name: 'Sentadilla completa con barra',
      description: 'Ponte de pie con los pies separados a la altura de los hombros, con los dedos de los pies ligeramente hacia afuera. Sujeta la barra sobre la parte superior de la espalda, apoyándola en los trapecios o los deltoides posteriores.',
      duration: '4 series de 8-10 reps',
      benefit: 'Fortalece cuádriceps y glúteos, clave para la potencia de salto y golpeo.',
      illustration: 'squat',
    },
    {
      name: 'Peso muerto con barra',
      description: 'Ponte de pie con los pies separados a la altura de los hombros y la barra en el suelo frente a ti. Flexiona las rodillas y las caderas para bajar el torso y agarra la barra con un agarre pronado, con las manos un poco más separadas que el ancho de los hombros.',
      duration: '4 series de 6-8 reps',
      benefit: 'Desarrolla la cadena posterior (glúteos e isquiotibiales), fundamental para sprints y cambios de ritmo.',
      illustration: 'hip_hinge',
    },
    {
      name: 'Peso muerto rumano con barra',
      description: 'Ponte de pie con los pies separados a la altura de los hombros y los dedos de los pies apuntando hacia delante. Sujeta la barra con un agarre pronado, manos un poco más separadas que el ancho de los hombros.',
      duration: '3-4 series de 8-10 reps',
      benefit: 'Fortalece isquiotibiales y glúteos, reduciendo el riesgo de lesión muscular en carrera.',
      illustration: 'hip_hinge',
    },
    {
      name: 'Zancada caminando',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Da un paso adelante con la pierna derecha, bajando el cuerpo a una posición de zancada.',
      duration: '3 series de 12 pasos por pierna',
      benefit: 'Mejora la fuerza unilateral de piernas y la estabilidad, esencial en duelos y cambios de dirección.',
      illustration: 'lunge',
    },
    {
      name: 'Plancha frontal con giro',
      description: 'Comienza en posición de plancha alta con las manos directamente debajo de los hombros y el cuerpo en línea recta de la cabeza a los pies. Activa el core y los glúteos para mantener una posición estable.',
      duration: '3 series de 10 giros por lado',
      benefit: 'Fortalece el core y la musculatura oblicua, mejorando la estabilidad en el contacto.',
      illustration: 'plank',
    },
    {
      name: 'Press de banca con barra',
      description: 'Túmbate sobre un banco con los pies apoyados en el suelo y la espalda presionada contra el banco. Agarra la barra con un agarre pronado un poco más ancho que la separación de los hombros.',
      duration: '4 series de 8-10 reps',
      benefit: 'Desarrolla fuerza en pecho, hombros y tríceps, útil para proteger el balón en el cuerpo a cuerpo.',
      illustration: 'bench_press',
    },
    {
      name: 'Press militar sentado con barra',
      description: 'Siéntate en un banco con la espalda recta y los pies planos sobre el suelo. Sujeta la barra con un agarre pronado, un poco más ancho que la separación de los hombros.',
      duration: '3-4 series de 8-10 reps',
      benefit: 'Fortalece hombros y tríceps, mejorando la fuerza en saltos y disputas aéreas.',
      illustration: 'shoulder_press',
    },
    {
      name: 'Remo invertido',
      description: 'Coloca una barra a la altura de la cintura o usa un entrenador de suspensión. Ponte de pie frente a la barra o al entrenador de suspensión, con los pies separados a la altura de los hombros.',
      duration: '3 series de 10-12 reps',
      benefit: 'Fortalece la espalda alta y bíceps, equilibrando el trabajo de empuje del tren superior.',
      illustration: 'row',
    },
    {
      name: 'Puente de glúteo con barra',
      description: 'Empieza tumbado boca arriba en el suelo con las rodillas flexionadas y los pies planos sobre el suelo. Coloca una barra sobre las caderas, sujetándola con firmeza con ambas manos.',
      duration: '4 series de 10-12 reps',
      benefit: 'Activa y fortalece los glúteos, clave para la potencia de aceleración.',
      illustration: 'hip_thrust',
    },
    {
      name: 'Elevación de cadera',
      description: 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Coloca las manos a los lados, con las palmas hacia abajo.',
      duration: '3 series de 15 reps',
      benefit: 'Fortalece glúteos y core sin necesidad de material, ideal para trabajo de activación.',
      illustration: 'hip_thrust',
    },
    {
      name: 'Flexiones de brazos',
      description: 'Comienza en una posición de plancha alta con las manos un poco más separadas que la anchura de los hombros y los pies juntos. Activa el core y baja el cuerpo hacia el suelo flexionando los codos, manteniendo el cuerpo en línea recta.',
      duration: '3-4 series de 12-15 reps',
      benefit: 'Fortalece pecho, hombros y tríceps con el propio peso corporal.',
      illustration: 'pushup',
    },
    {
      name: 'Flexiones diamante',
      description: 'Comienza en posición de plancha alta con las manos juntas, formando una figura de diamante con los pulgares y los índices. Mantén el cuerpo en línea recta de la cabeza a los pies, activando el core y los glúteos.',
      duration: '3 series de 10-12 reps',
      benefit: 'Enfatiza el trabajo de tríceps, útil para la fuerza de empuje en el juego aéreo.',
      illustration: 'pushup',
    },
    {
      name: 'Giro ruso',
      description: 'Siéntate en el suelo con las rodillas flexionadas y los pies apoyados en el suelo. Inclínate ligeramente hacia atrás manteniendo la espalda recta y el core activado.',
      duration: '3 series de 20 reps (10 por lado)',
      benefit: 'Fortalece los oblicuos, mejorando la rotación de tronco en el golpeo.',
      illustration: 'plank',
    },
    {
      name: 'Elevación de piernas colgado',
      description: 'Cuélgate de una barra de dominadas con los brazos completamente extendidos y las palmas mirando hacia afuera. Activa el core y levanta las piernas frente a ti, manteniéndolas rectas.',
      duration: '3 series de 10-12 reps',
      benefit: 'Fortalece el core inferior, clave para la estabilidad en el disparo y el salto.',
      illustration: 'plank',
    },
    {
      name: 'Dominadas',
      description: 'Cuélgate de una barra de dominadas con las palmas hacia afuera y los brazos completamente extendidos. Activa el core y junta los omóplatos.',
      duration: '3-4 series al fallo',
      benefit: 'Desarrolla dorsales y bíceps, mejorando la fuerza general del tren superior.',
      illustration: 'row',
    },
    {
      name: 'Flexiones en TRX',
      description: 'Busca un entrenador de suspensión y ajústalo a una altura adecuada. Ponte de pie de espaldas al punto de anclaje y sostén las asas con un agarre prono.',
      duration: '3 series de 10-12 reps',
      benefit: 'Trabaja pecho y core con inestabilidad añadida, mejorando el control corporal.',
      illustration: 'pushup',
    },
    {
      name: 'Peso muerto sumo con barra',
      description: 'Ponte de pie con los pies más separados que el ancho de los hombros, con las puntas de los pies hacia afuera. Coloca una barra en el suelo frente a ti, centrada entre los pies.',
      duration: '4 series de 6-8 reps',
      benefit: 'Fortalece glúteos e isquiotibiales con énfasis en la parte interna del muslo.',
      illustration: 'hip_hinge',
    },
    {
      name: 'Zancada con mancuernas',
      description: 'Ponte de pie con los pies separados a la altura de los hombros, sujetando una mancuerna en cada mano. Da un paso adelante con el pie derecho, bajando el cuerpo hasta una posición de zancada.',
      duration: '3 series de 10 reps por pierna',
      benefit: 'Añade carga externa a la zancada, aumentando la fuerza y potencia unilateral.',
      illustration: 'lunge',
    },
    {
      name: 'Plancha lateral con aducción de cadera',
      description: 'Comienza tumbado de lado con las piernas extendidas y apiladas una sobre la otra. Apóyate sobre el antebrazo, manteniendo el codo directamente debajo del hombro.',
      duration: '3 series de 10-12 reps por lado',
      benefit: 'Fortalece oblicuos y aductores, protegiendo la cadera en cambios de dirección.',
      illustration: 'plank',
    },
  ],

  tactico: [
    {
      name: 'Rondo de posesión',
      description: 'Círculo de jugadores manteniendo posesión contra defensores en el centro.',
      duration: '15-20 minutos',
      benefit: 'Mejora toma de decisiones bajo presión y trabajo en equipo',
      illustration: 'field_rondo',
    },
    {
      name: 'Juego de posición',
      description: 'Ejercicio de posesión en espacios reducidos con superioridad numérica.',
      duration: '20 minutos',
      benefit: 'Desarrolla automatismos de juego y movimientos colectivos',
      illustration: 'field_positions',
    },
    {
      name: 'Situaciones de 2v1 y 3v2',
      description: 'Superioridades numéricas en espacios reducidos para finalización.',
      duration: '15 minutos',
      benefit: 'Mejora asociación ofensiva y definición',
      illustration: 'field_2v1',
    },
    {
      name: 'Transiciones defensa-ataque',
      description: 'Recuperación de balón y ataque rápido en diferentes zonas del campo.',
      duration: '20 minutos',
      benefit: 'Desarrolla rapidez mental y cambio de chip',
      illustration: 'field_transition',
    },
    {
      name: 'Salida de presión desde atrás',
      description: 'Práctica de construcción de juego contra pressing rival organizado.',
      duration: '25 minutos',
      benefit: 'Mejora circulación bajo presión y toma de decisiones',
      illustration: 'field_buildup',
    },
    {
      name: 'Defensas de línea y fuera de juego',
      description: 'Sincronización de línea defensiva con activación de fuera de juego.',
      duration: '20 minutos',
      benefit: 'Coordinación defensiva y comunicación entre líneas',
      illustration: 'field_defensive',
    },
    {
      name: 'Juego de bandas y centros',
      description: 'Progresión por banda, desmarques y remate de centros al área.',
      duration: '25 minutos',
      benefit: 'Perfecciona juego exterior y movimientos en área',
      illustration: 'field_wide',
    },
    {
      name: 'Finalización tras robo',
      description: 'Presión alta, recuperación y remate inmediato con superioridad.',
      duration: '20 minutos',
      benefit: 'Desarrolla mentalidad de contragolpe rápido',
      illustration: 'field_counter',
    },
    {
      name: 'Balones divididos y segundas jugadas',
      description: 'Disputas aéreas y llegada a rechaces en zona de finalización.',
      duration: '15 minutos',
      benefit: 'Mejora agresividad ofensiva y anticipación',
      illustration: 'field_2v1',
    },
    {
      name: 'Organización en defensa de córneres',
      description: 'Marcaje zonal y mixto en jugadas de estrategia defensiva.',
      duration: '15 minutos',
      benefit: 'Reduce goles en contra por jugadas a balón parado',
      illustration: 'field_corner',
    },
    {
      name: 'Circulación y cambio de orientación',
      description: 'Ejercicio de posesión con cambios de banda para desestabilizar.',
      duration: '20 minutos',
      benefit: 'Amplía visión de juego y genera espacios',
      illustration: 'field_positions',
    },
    {
      name: 'Repliegue intensivo organizado',
      description: 'Retroceso ordenado tras pérdida con basculación y coberturas.',
      duration: '20 minutos',
      benefit: 'Organización defensiva y prevención de contragolpes',
      illustration: 'field_defensive',
    },
    {
      name: 'Small-Sided Game 3v3 con porteros neutros',
      description: 'Partido reducido 3 contra 3 en espacio de 20×30m con dos porteros neutrales que juegan siempre con el equipo en posesión. Genera superioridad permanente y obliga a la toma de decisiones rápida (SSG — Small-Sided Games, Grupo Campus).',
      duration: '4 series de 5 minutos con 2 min descanso',
      benefit: 'Intensidad máxima de toma de decisiones y automatismos colectivos de posesión',
      illustration: 'field_ssg',
    },
    {
      name: 'Pressing organizado con triggers',
      description: 'Definir señales de pressing (trigger: pase hacia atrás, mal control, portero con balón). El equipo sin balón activa pressing inmediato al darse el trigger. Ejercicio progresivo 6v6 en medio campo.',
      duration: '25 minutos',
      benefit: 'Crea pressing automático y coordinado, reduciendo espacios de construcción rival',
      illustration: 'field_press',
    },
    {
      name: 'Posesión con líneas de pase prohibidas',
      description: 'Juego de posesión 5v2 o 6v3 donde se prohíbe el pase atrás o el pase lateral según la zona. Obliga a buscar siempre la línea de pase progresiva.',
      duration: '20 minutos',
      benefit: 'Desarrolla verticalidad y visión de pase progresivo bajo presión',
      illustration: 'field_positions',
    },
    {
      name: 'Transición 4v4 con portero',
      description: 'Dos equipos de 4 jugadores más portero en medio campo. Tras robo, ataque inmediato al arco contrario. La velocidad de transición es el objetivo principal.',
      duration: '4 series de 6 minutos',
      benefit: 'Automatiza cambio de rol defensa-ataque y mejora velocidad de transición',
      illustration: 'field_transition',
    },
    {
      name: 'Pérdida y presión inmediata (6 segundos)',
      description: 'Ejercicio de posesión donde el equipo que pierde el balón tiene 6 segundos para recuperarlo. Basado en el principio de Gegenpressing (Klopp/Rangnick). Si no lo recupera, se reinicia.',
      duration: '20 minutos',
      benefit: 'Desarrolla respuesta agresiva e inmediata ante la pérdida del balón',
      illustration: 'field_press',
    },
    {
      name: 'Construcción con superioridad atrás (GK+3 vs 2)',
      description: 'El equipo en posesión sale desde el portero con tres defensas contra dos presionadores. Obliga a encontrar soluciones de circulación y progresión de forma organizada.',
      duration: '20 minutos',
      benefit: 'Mejora construcción desde atrás y confianza de la línea defensiva con balón',
      illustration: 'field_buildup',
    },
    {
      name: 'Timing en córner atacante',
      description: 'Práctica específica de córners ofensivos: señales de movimiento, bloques, arrastres y llegadas a zona de remate. Se trabajan 4-5 variantes codificadas.',
      duration: '15 minutos (series de repeticiones)',
      benefit: 'Incrementa efectividad en jugadas de estrategia ofensiva y goles a balón parado',
      illustration: 'field_corner',
    },
    {
      name: 'Cobertura y vigilancia defensiva',
      description: 'Ejercicio defensivo 4v4 en espacio cerrado donde se trabajan las posiciones de cobertura (detrás del compañero) y vigilancia (orientado para ver balón y rival simultáneamente).',
      duration: '20 minutos',
      benefit: 'Solidez defensiva colectiva y comunicación entre líneas',
      illustration: 'field_defensive',
    },
  ],

  resistencia: [
    {
      name: 'Carrera continua',
      description: 'Comienza de pie con los pies separados a la altura de la cadera. Activa el core y mantén la parte superior del cuerpo relajada.',
      duration: '15-20 minutos a ritmo moderado',
      benefit: 'Mejora la resistencia cardiovascular base necesaria para los 90 minutos de partido.',
      illustration: 'run',
    },
    {
      name: 'Escalador (mountain climber)',
      description: 'Comienza en una posición de plancha alta con las manos justo debajo de los hombros y el cuerpo en línea recta. Activa el core y lleva la rodilla derecha hacia el pecho, luego cambia rápidamente y lleva la rodilla izquierda hacia el pecho.',
      duration: '3 series de 30-40 segundos',
      benefit: 'Combina trabajo cardiovascular con activación de core a alta intensidad.',
      illustration: 'mountain_climber',
    },
    {
      name: 'Rodillas altas en pared',
      description: 'Ponte de pie frente a una pared con los pies separados a la altura de las caderas. Coloca las manos en la pared para mayor apoyo.',
      duration: '3 series de 20-30 segundos',
      benefit: 'Mejora la frecuencia de zancada y la coordinación de carrera.',
      illustration: 'sprint',
    },
    {
      name: 'Carrera de pasos cortos',
      description: 'Busca un espacio abierto o una cinta de correr para realizar el ejercicio. Ponte de pie con los pies separados a la altura de la cadera.',
      duration: '4 series de 20 metros',
      benefit: 'Trabaja la frecuencia de piernas, útil para arrancadas rápidas.',
      illustration: 'sprint',
    },
    {
      name: 'Zancada con rodilla alta caminando',
      description: 'Ponte de pie con los pies separados a la altura de la cadera. Levanta la rodilla derecha hacia el pecho lo más alto que puedas mientras mantienes el equilibrio sobre la pierna izquierda.',
      duration: '3 series de 10 pasos por pierna',
      benefit: 'Combina movilidad de cadera con resistencia, ideal para el calentamiento.',
      illustration: 'lunge',
    },
    {
      name: 'Desplazamiento en oso (bear crawl)',
      description: 'Comienza apoyado sobre manos y rodillas, con las manos justo debajo de los hombros y las rodillas justo debajo de las caderas. Levanta las rodillas ligeramente del suelo, manteniendo la espalda plana y el core activado.',
      duration: '3 series de 15-20 metros',
      benefit: 'Desarrolla resistencia de todo el cuerpo y estabilidad del core.',
      illustration: 'mountain_climber',
    },
    {
      name: 'Paso de esquí lateral',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Dobla ligeramente las rodillas y mantén la espalda recta.',
      duration: '3 series de 30 segundos',
      benefit: 'Mejora la resistencia y agilidad lateral, útil en el marcaje.',
      illustration: 'jump_lateral',
    },
    {
      name: 'Paso adelante-atrás',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Da un paso adelante con el pie derecho, flexionando la rodilla y bajando el cuerpo hacia una posición de zancada.',
      duration: '3 series de 30 segundos',
      benefit: 'Trabaja la resistencia y el control en cambios de dirección cortos.',
      illustration: 'lunge',
    },
    {
      name: 'Flexión y carrera en el sitio',
      description: 'Comienza en posición de flexión con las manos separadas a la altura de los hombros y el cuerpo en línea recta. Baja el pecho hacia el suelo flexionando los codos, manteniendo el cuerpo recto.',
      duration: '3 series de 30-40 segundos',
      benefit: 'Combina fuerza y cardio, simulando la fatiga tras un contacto en el suelo.',
      illustration: 'mountain_climber',
    },
    {
      name: 'Giro de brazos 360',
      description: 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Mantén los brazos extendidos rectos frente a ti, paralelos al suelo.',
      duration: '3 series de 30 segundos',
      benefit: 'Mejora la movilidad de tronco y la resistencia del core en rotación.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Rueda abdominal con extensión',
      description: 'Comienza en posición de plancha con las manos sobre el rodillo y el cuerpo recto. Activa el core y comienza a hacer rodar el rodillo hacia adelante extendiendo los brazos.',
      duration: '3 series de 10-12 reps',
      benefit: 'Trabaja la resistencia del core y la estabilidad del tronco.',
      illustration: 'plank',
    },
    {
      name: 'Bicicleta elíptica',
      description: 'Ajusta la altura del asiento y colócate en la bicicleta elíptica. Coloca los pies en los pedales y sujeta el manillar.',
      duration: '15-20 minutos a intensidad moderada',
      benefit: 'Entrenamiento cardiovascular de bajo impacto, ideal para la recuperación activa.',
      illustration: 'run',
    },
    {
      name: 'Caminata inclinada en cinta',
      description: 'Ajusta el nivel de inclinación de la cinta de correr a la intensidad deseada. Ponte de pie sobre la cinta de correr con los pies separados a la altura de los hombros.',
      duration: '15-20 minutos',
      benefit: 'Mejora la resistencia aeróbica y la fuerza de piernas con bajo impacto articular.',
      illustration: 'run',
    },
    {
      name: 'Bicicleta estática suave',
      description: 'Ajusta la altura y la posición del asiento en la bicicleta estática para asegurar una alineación correcta. Coloca los pies sobre los pedales y sujétalos con las correas si están disponibles.',
      duration: '15-20 minutos',
      benefit: 'Entrenamiento aeróbico de baja intensidad, útil en la vuelta a la calma.',
      illustration: 'run',
    },
    {
      name: 'Bicicleta estática intensa',
      description: 'Ajusta la altura y la posición del asiento para asegurar una alineación correcta. Coloca los pies sobre los pedales y sujétalos con las correas si están disponibles.',
      duration: '15-20 minutos con cambios de ritmo',
      benefit: 'Mejora la capacidad aeróbica y la tolerancia a esfuerzos sostenidos.',
      illustration: 'run',
    },
  ],

  pliometria: [
    {
      name: 'Salto adelante',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Flexiona las rodillas y baja el cuerpo hacia una posición de sentadilla.',
      duration: '3 series de 8-10 reps',
      benefit: 'Desarrolla la potencia horizontal, clave para arrancadas explosivas.',
      illustration: 'squat_jump',
    },
    {
      name: 'Salto atrás',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Flexiona ligeramente las rodillas y salta hacia atrás, impulsándote con ambos pies.',
      duration: '3 series de 8-10 reps',
      benefit: 'Mejora el control excéntrico y la potencia en desplazamientos hacia atrás.',
      illustration: 'squat_jump',
    },
    {
      name: 'Sentadilla con salto',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y empujando las caderas hacia atrás.',
      duration: '4 series de 8-10 reps',
      benefit: 'Desarrolla la potencia de piernas para saltos y arrancadas.',
      illustration: 'squat_jump',
    },
    {
      name: 'Sentadilla con salto y caída',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y empujando las caderas hacia atrás.',
      duration: '3 series de 8 reps',
      benefit: 'Trabaja la capacidad reactiva de las piernas tras el impacto del salto.',
      illustration: 'squat_jump',
    },
    {
      name: 'Sentadilla con salto y barra',
      description: 'Empieza de pie con los pies separados a la altura de los hombros, sujetando una barra sobre la parte superior de la espalda. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y empujando las caderas hacia atrás.',
      duration: '3-4 series de 6-8 reps',
      benefit: 'Añade carga al salto, aumentando la potencia explosiva de piernas.',
      illustration: 'squat_jump',
    },
    {
      name: 'Sentadilla pliométrica con mancuernas',
      description: 'Ponte de pie con los pies separados a la altura de los hombros, sosteniendo una mancuerna en cada mano a los costados. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y empujando las caderas hacia atrás.',
      duration: '3 series de 8 reps por lado',
      benefit: 'Combina fuerza y potencia con cambio de apoyo en el aire.',
      illustration: 'squat_jump',
    },
    {
      name: 'Zancada con salto',
      description: 'Comienza de pie con los pies separados a la altura de los hombros. Da un paso adelante con el pie derecho, bajando el cuerpo hasta una posición de zancada.',
      duration: '3 series de 8-10 reps por lado',
      benefit: 'Desarrolla potencia unilateral, esencial en cambios de dirección explosivos.',
      illustration: 'jump_lateral',
    },
    {
      name: 'Salto a caja con estabilización a una pierna',
      description: 'Ponte de pie frente a una caja o plataforma con los pies separados a la altura de los hombros. Flexiona las rodillas y salta sobre la caja, aterrizando suavemente con un pie sobre la caja y el otro pie colgando del borde.',
      duration: '3 series de 6 reps por pierna',
      benefit: 'Mejora la absorción de impacto y la estabilidad de tobillo y rodilla.',
      illustration: 'depth_jump',
    },
    {
      name: 'Saltos de patinador (skater hops)',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Dobla ligeramente las rodillas y salta hacia la derecha, aterrizando sobre el pie derecho.',
      duration: '3 series de 10 reps por lado',
      benefit: 'Desarrolla potencia y estabilidad lateral, clave en el regate y el marcaje.',
      illustration: 'jump_lateral',
    },
    {
      name: 'Comba (cuerda de saltar)',
      description: 'Sujeta las asas de la cuerda de saltar con las manos, palmas hacia adentro. Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas.',
      duration: '3 series de 1 minuto',
      benefit: 'Mejora la coordinación y la capacidad reactiva del tren inferior.',
      illustration: 'skipping',
    },
    {
      name: 'Burpee',
      description: 'Comienza de pie con los pies separados a la altura de los hombros. Baja el cuerpo hacia una posición de sentadilla flexionando las rodillas y colocando las manos en el suelo frente a ti.',
      duration: '3 series de 10-12 reps',
      benefit: 'Ejercicio de cuerpo completo que combina fuerza, potencia y resistencia.',
      illustration: 'squat_jump',
    },
    {
      name: 'Flexión con palmada',
      description: 'Comienza en posición de plancha alta con las manos un poco más separadas que el ancho de los hombros. Baja el cuerpo hacia el suelo flexionando los codos, manteniendo el core activado.',
      duration: '3 series de 6-8 reps',
      benefit: 'Desarrolla potencia explosiva en el tren superior.',
      illustration: 'pushup',
    },
    {
      name: 'Flexión pliométrica',
      description: 'Comienza en posición de plancha alta con las manos un poco más separadas que el ancho de los hombros. Baja el pecho hacia el suelo flexionando los codos, manteniendo el cuerpo en línea recta.',
      duration: '3 series de 6-8 reps',
      benefit: 'Mejora la fuerza explosiva de empuje, útil en caídas y contactos.',
      illustration: 'pushup',
    },
    {
      name: 'Flexión inclinada con salto en profundidad',
      description: 'Busca una superficie elevada, como un banco o un escalón, y coloca las manos separadas a la altura de los hombros en el borde. Da un paso hacia atrás con los pies, manteniendo el cuerpo en línea recta desde la cabeza hasta los talones.',
      duration: '3 series de 6-8 reps',
      benefit: 'Combina fuerza de empuje con trabajo pliométrico controlado.',
      illustration: 'pushup',
    },
    {
      name: 'Salto estrella',
      description: 'Ponte de pie con los pies separados a la altura de los hombros y los brazos a los costados. Flexiona ligeramente las rodillas y salta hacia arriba de forma explosiva.',
      duration: '3 series de 10-12 reps',
      benefit: 'Ejercicio explosivo de cuerpo completo que mejora la coordinación.',
      illustration: 'squat_jump',
    },
    {
      name: 'Saltos de tijera',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Salta del suelo y al mismo tiempo cruza la pierna derecha por delante de la pierna izquierda.',
      duration: '3 series de 30 segundos',
      benefit: 'Desarrolla potencia y coordinación en el tren inferior.',
      illustration: 'jump_lateral',
    },
    {
      name: 'Salto de sentadilla parcial',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Flexiona las rodillas y baja el cuerpo hacia una posición de sentadilla.',
      duration: '3 series de 10-12 reps',
      benefit: 'Trabaja la potencia de salto con menor rango de movimiento, ideal para series rápidas.',
      illustration: 'squat_jump',
    },
    {
      name: 'Saltos en tijera abierta',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Flexiona las rodillas y baja el cuerpo hacia una posición de sentadilla.',
      duration: '3 series de 10-12 reps',
      benefit: 'Mejora la coordinación y la potencia general del tren inferior.',
      illustration: 'squat_jump',
    },
  ],

  prevencion: [
    {
      name: 'Estiramiento de isquiotibiales',
      description: 'Ponte de pie con los pies separados a la altura de los hombros. Da un paso adelante con el pie derecho y traslada el peso hacia la pierna derecha.',
      duration: '20-30 segundos por pierna',
      benefit: 'Mejora la flexibilidad de la parte posterior del muslo, reduciendo el riesgo de lesión.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de gemelos en pared',
      description: 'Ponte de pie frente a una pared con los pies separados a la altura de las caderas. Coloca las manos contra la pared a la altura de los hombros.',
      duration: '20-30 segundos por pierna',
      benefit: 'Previene sobrecargas en la pantorrilla, frecuentes en carrera y salto.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de glúteo sentado',
      description: 'Siéntate en el suelo con las piernas extendidas frente a ti. Dobla la rodilla derecha y cruza el tobillo derecho sobre el muslo izquierdo.',
      duration: '30-60 segundos por lado',
      benefit: 'Libera tensión en el glúteo, mejorando la movilidad de cadera.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de pecho y hombro',
      description: 'Ponte de pie con la espalda recta y los pies separados a la altura de los hombros. Extiende los brazos rectos frente a ti a la altura de los hombros.',
      duration: '20-30 segundos',
      benefit: 'Mejora la postura y libera tensión en el tren superior.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de dorsal arrodillado',
      description: 'Arrodíllate en el suelo con las rodillas separadas a la altura de las caderas y los dedos de los pies apuntando hacia atrás. Extiende los brazos por encima de la cabeza y entrelaza los dedos.',
      duration: '20-30 segundos por lado',
      benefit: 'Mejora la movilidad de la espalda y el rango de los brazos.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento del mundo (world\'s greatest stretch)',
      description: 'Comienza en posición de zancada con el pie derecho adelante y el pie izquierdo atrás. Coloca las manos en el suelo a ambos lados de tu pie derecho.',
      duration: '30-45 segundos por lado',
      benefit: 'Estiramiento completo de cadera, isquiotibiales y tronco en un solo movimiento.',
      illustration: 'hip_mobility',
    },
    {
      name: 'Estiramiento lateral de pie',
      description: 'Ponte de pie con los pies separados a la altura de los hombros y las rodillas ligeramente flexionadas. Extiende los brazos hacia los lados, paralelos al suelo.',
      duration: '15-30 segundos por lado',
      benefit: 'Mejora la movilidad del tronco y libera el costado.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de columna',
      description: 'Siéntate en el suelo con las piernas extendidas frente a ti. Coloca las manos en el suelo detrás de ti, con los dedos apuntando hacia tu cuerpo.',
      duration: '3 series de 8-10 reps',
      benefit: 'Mejora la movilidad de la columna, útil tras cargas de entrenamiento.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de tríceps',
      description: 'Ponte de pie o siéntate erguido con la espalda recta. Extiende un brazo por encima de la cabeza, flexionándolo por el codo.',
      duration: '15-30 segundos por brazo',
      benefit: 'Libera tensión en el brazo, útil en la recuperación del tren superior.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de deltoides posterior',
      description: 'Ponte de pie con la espalda recta y los pies separados a la altura de los hombros. Extiende el brazo derecho a través del pecho, colocando la mano izquierda sobre el codo derecho.',
      duration: '15-30 segundos por lado',
      benefit: 'Mejora la movilidad del hombro, reduciendo tensión postural.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de cadera con rodillo',
      description: 'Comienza sentándote en el suelo con las piernas extendidas frente a ti. Coloca el rodillo debajo de los glúteos, justo por encima de las rodillas.',
      duration: '3 series de 10 reps',
      benefit: 'Libera tensión en glúteos e isquiotibiales usando foam roller.',
      illustration: 'foam_roll',
    },
    {
      name: 'Estiramiento de espalda con rodillo',
      description: 'Comienza sentándote en el suelo con las piernas extendidas frente a ti. Coloca el rodillo perpendicular a tu cuerpo, justo debajo de los glúteos.',
      duration: '3 series de 8-10 reps',
      benefit: 'Mejora la movilidad de la columna y libera tensión en la espalda.',
      illustration: 'foam_roll',
    },
    {
      name: 'Estiramiento cruz de hierro',
      description: 'Túmbate boca arriba con los brazos extendidos hacia los lados. Levanta las piernas hacia el techo, manteniéndolas rectas.',
      duration: '3 series por lado',
      benefit: 'Mejora la movilidad de cadera y core en rotación.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento del corredor',
      description: 'Ponte de pie con los pies separados a la altura de la cadera. Da un paso hacia delante con el pie derecho, manteniendo el pie izquierdo firme en el suelo.',
      duration: '20-30 segundos por lado',
      benefit: 'Estira cadera e isquiotibiales, clave tras sesiones de carrera.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento lateral de cuello',
      description: 'Ponte de pie o siéntate erguido con los hombros relajados. Inclina la cabeza hacia un lado, llevando la oreja hacia el hombro.',
      duration: '15-30 segundos por lado, 2-4 series',
      benefit: 'Libera tensión cervical acumulada tras el entrenamiento.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de cuádriceps tumbado',
      description: 'Túmbate de lado con las piernas rectas. Flexiona la pierna de arriba y agarra tu tobillo o pie con la mano.',
      duration: '20-30 segundos por pierna',
      benefit: 'Mejora la flexibilidad del cuádriceps, reduciendo tensión en la rodilla.',
      illustration: 'stretch_dynamic',
    },
    {
      name: 'Estiramiento de flexor de cadera con balón',
      description: 'Coloca el balón de estabilidad en el suelo y arrodíllate frente a él. Coloca el pie derecho sobre el balón de estabilidad, con la rodilla flexionada en un ángulo de 90 grados.',
      duration: '20-30 segundos por lado',
      benefit: 'Libera el flexor de cadera, frecuente en futbolistas por el gesto de golpeo.',
      illustration: 'hip_mobility',
    },
    {
      name: 'Estiramiento de cuádriceps a cuatro apoyos',
      description: 'Comienza apoyado sobre manos y rodillas, con las manos justo debajo de los hombros y las rodillas justo debajo de las caderas. Extiende una pierna hacia atrás, manteniendo la rodilla flexionada y el pie en flexión.',
      duration: '20-30 segundos por lado',
      benefit: 'Mejora la flexibilidad de cuádriceps y cadera.',
      illustration: 'hip_mobility',
    },
    {
      name: 'Estiramiento de isquiotibiales y gemelo con banda',
      description: 'Ponte de pie con la espalda recta y los pies separados a la altura de los hombros. Sostén la correa con ambas manos y colócala alrededor de la parte anterior de la planta del pie.',
      duration: '20-30 segundos por pierna',
      benefit: 'Combina el estiramiento de isquiotibiales y pantorrilla con ayuda de banda.',
      illustration: 'band_walk',
    },
    {
      name: 'Tabla de equilibrio',
      description: 'Coloca la tabla de equilibrio sobre una superficie plana. Sube a la tabla de equilibrio con un pie, asegurándote de que esté centrado.',
      duration: '3 series de 30-45 segundos por pierna',
      benefit: 'Mejora la propiocepción y estabilidad del tobillo, clave en la prevención de esguinces.',
      illustration: 'balance_single',
    },
    {
      name: 'Puente a una pierna con pierna extendida',
      description: 'Túmbate sobre tu espalda con las rodillas flexionadas y los pies apoyados en el suelo. Extiende una pierna recta hacia delante.',
      duration: '3 series de 10-12 reps por lado',
      benefit: 'Fortalece glúteo e isquiotibial de forma unilateral, mejorando la estabilidad.',
      illustration: 'hip_thrust',
    },
    {
      name: 'Estiramiento de piriforme sentado',
      description: 'Siéntate en el suelo con las piernas extendidas frente a ti. Dobla la rodilla derecha y coloca el pie derecho en la parte exterior de la rodilla izquierda.',
      duration: '20-30 segundos por lado',
      benefit: 'Libera tensión profunda en el glúteo, reduciendo molestias en cadera y zona lumbar.',
      illustration: 'stretch_dynamic',
    },
  ],
};
