-- ══════════════════════════════════════════════════════════
-- Seed exercises (86 entries from src/constants/training.ts)
-- ══════════════════════════════════════════════════════════
INSERT INTO exercises (name, description, duration, benefit, illustration, category) VALUES

-- fuerza (18)
('Sentadillas con peso', 'Fortalece cuádriceps, glúteos e isquiotibiales. Fundamental para potencia de salto y sprint.', '3 series de 10-12 reps', 'Aumenta fuerza de piernas y potencia explosiva', 'squat', 'fuerza'),
('Core con balón medicinal', 'Rotaciones, lanzamientos y ejercicios de estabilidad con balón medicinal.', '4 series de 15 reps', 'Fortalece el core para mejor equilibrio y protección de espalda', 'mountain_climber', 'fuerza'),
('Trabajo de aductores', 'Fortalecimiento específico de aductores con máquina o bandas elásticas.', '3 series de 12 reps', 'Previene pubalgias y mejora cambios de dirección', 'copenhagen', 'fuerza'),
('Peso muerto rumano', 'Fortalecimiento de cadena posterior: isquiotibiales, glúteos y espalda baja.', '4 series de 8-10 reps', 'Aumenta potencia de sprint y previene lesiones isquiotibiales', 'hip_hinge', 'fuerza'),
('Estocadas con salto', 'Estocadas explosivas alternando piernas con impulso hacia arriba.', '3 series de 12 reps por pierna', 'Desarrolla potencia unilateral y equilibrio dinámico', 'lunge', 'fuerza'),
('Plancha isométrica con variantes', 'Planchas frontales, laterales y con elevación de extremidades.', '4 series de 45-60 segundos', 'Estabilidad del core y resistencia muscular', 'plank', 'fuerza'),
('Press de banca', 'Fortalecimiento del tren superior: pecho, hombros y tríceps.', '3 series de 10 reps', 'Mejora fuerza en disputas y protección del balón', 'bench_press', 'fuerza'),
('Trabajo con TRX', 'Ejercicios de suspensión para fuerza funcional y estabilidad.', '3 series de 12-15 reps', 'Fortalece músculos estabilizadores y mejora propiocepción', 'row', 'fuerza'),
('Escaladores con velocidad', 'Mountain climbers a alta velocidad manteniendo técnica correcta.', '4 series de 30 segundos', 'Combina fuerza de core con acondicionamiento', 'mountain_climber', 'fuerza'),
('Hip Thrust con barra', 'Empuje de cadera con barra sobre banco. Activa glúteos máximos de forma específica replicando el patrón de extensión de cadera del sprint.', '4 series de 10-12 reps', 'Máxima activación de glúteos para mejorar aceleración y potencia de sprint', 'hip_thrust', 'fuerza'),
('Sentadilla búlgara', 'Sentadilla unilateral con pie trasero elevado en banco. Exige mayor estabilidad y equilibrio que la sentadilla bilateral, replicando el apoyo monopodal del fútbol.', '3 series de 10 reps por pierna', 'Fuerza unilateral para cambios de dirección y prevención de asimetrías', 'squat', 'fuerza'),
('Curl nórdico de isquiotibiales', 'Ejercicio excéntrico de isquiotibiales: de rodillas, bajar el cuerpo controladamente usando solo la musculatura posterior. Método validado científicamente (Arnason, Mjølsnes).', '3 series de 6-8 reps', 'Gold standard de prevención de roturas musculares de isquiotibiales', 'nordic_curl', 'fuerza'),
('Press militar', 'Empuje vertical de barra o mancuernas desde hombros hasta extensión completa. Fortalece deltoides, trapecios y tríceps.', '3 series de 10-12 reps', 'Fuerza de tren superior para disputas aéreas y rechaces', 'shoulder_press', 'fuerza'),
('Remo con barra', 'Tirón horizontal desde posición inclinada. Trabaja la cadena posterior superior: dorsales, romboides y bíceps. Mejora la postura bajo presión.', '4 series de 10 reps', 'Equilibrio muscular tren superior y mejora de postura en carrera', 'row', 'fuerza'),
('Puente de glúteo a una pierna', 'Desde posición supina con una pierna elevada, empuje de cadera con la pierna de apoyo. Activa glúteo medio y mayor de forma aislada.', '3 series de 15 reps por pierna', 'Estabilidad pélvica y activación de glúteo para prevenir valgo de rodilla', 'hip_thrust', 'fuerza'),
('Extensión de cadera con cable', 'De pie, extensión de cadera contra resistencia de cable en polea baja. Replica el patrón motor del sprint con resistencia externa progresiva.', '3 series de 12-15 reps por pierna', 'Fortalece el patrón neuromotor específico del sprint y la aceleración', 'cable_extension', 'fuerza'),
('Flexiones explosivas con palmada', 'Flexiones con impulso explosivo suficiente para separar las manos del suelo y dar una palmada. Desarrolla potencia del tren superior.', '4 series de 8-10 reps', 'Potencia explosiva del tren superior para disputas, faltas y protección del balón', 'pushup', 'fuerza'),
('Sentadilla con salto', 'Sentadilla hasta paralelo seguida de salto explosivo máximo. Combina fuerza y velocidad en un movimiento compuesto (Bosco, 1994).', '3 series de 10 saltos', 'Desarrolla potencia reactiva y capacidad elástica del músculo', 'squat_jump', 'fuerza'),

-- tactico (20)
('Rondo de posesión', 'Círculo de jugadores manteniendo posesión contra defensores en el centro.', '15-20 minutos', 'Mejora toma de decisiones bajo presión y trabajo en equipo', 'field_rondo', 'tactico'),
('Juego de posición', 'Ejercicio de posesión en espacios reducidos con superioridad numérica.', '20 minutos', 'Desarrolla automatismos de juego y movimientos colectivos', 'field_positions', 'tactico'),
('Situaciones de 2v1 y 3v2', 'Superioridades numéricas en espacios reducidos para finalización.', '15 minutos', 'Mejora asociación ofensiva y definición', 'field_2v1', 'tactico'),
('Transiciones defensa-ataque', 'Recuperación de balón y ataque rápido en diferentes zonas del campo.', '20 minutos', 'Desarrolla rapidez mental y cambio de chip', 'field_transition', 'tactico'),
('Salida de presión desde atrás', 'Práctica de construcción de juego contra pressing rival organizado.', '25 minutos', 'Mejora circulación bajo presión y toma de decisiones', 'field_buildup', 'tactico'),
('Defensas de línea y fuera de juego', 'Sincronización de línea defensiva con activación de fuera de juego.', '20 minutos', 'Coordinación defensiva y comunicación entre líneas', 'field_defensive', 'tactico'),
('Juego de bandas y centros', 'Progresión por banda, desmarques y remate de centros al área.', '25 minutos', 'Perfecciona juego exterior y movimientos en área', 'field_wide', 'tactico'),
('Finalización tras robo', 'Presión alta, recuperación y remate inmediato con superioridad.', '20 minutos', 'Desarrolla mentalidad de contragolpe rápido', 'field_counter', 'tactico'),
('Balones divididos y segundas jugadas', 'Disputas aéreas y llegada a rechaces en zona de finalización.', '15 minutos', 'Mejora agresividad ofensiva y anticipación', 'field_2v1', 'tactico'),
('Organización en defensa de córneres', 'Marcaje zonal y mixto en jugadas de estrategia defensiva.', '15 minutos', 'Reduce goles en contra por jugadas a balón parado', 'field_corner', 'tactico'),
('Circulación y cambio de orientación', 'Ejercicio de posesión con cambios de banda para desestabilizar.', '20 minutos', 'Amplía visión de juego y genera espacios', 'field_positions', 'tactico'),
('Repliegue intensivo organizado', 'Retroceso ordenado tras pérdida con basculación y coberturas.', '20 minutos', 'Organización defensiva y prevención de contragolpes', 'field_defensive', 'tactico'),
('Small-Sided Game 3v3 con porteros neutros', 'Partido reducido 3 contra 3 en espacio de 20×30m con dos porteros neutrales que juegan siempre con el equipo en posesión. Genera superioridad permanente y obliga a la toma de decisiones rápida (SSG — Small-Sided Games, Grupo Campus).', '4 series de 5 minutos con 2 min descanso', 'Intensidad máxima de toma de decisiones y automatismos colectivos de posesión', 'field_ssg', 'tactico'),
('Pressing organizado con triggers', 'Definir señales de pressing (trigger: pase hacia atrás, mal control, portero con balón). El equipo sin balón activa pressing inmediato al darse el trigger. Ejercicio progresivo 6v6 en medio campo.', '25 minutos', 'Crea pressing automático y coordinado, reduciendo espacios de construcción rival', 'field_press', 'tactico'),
('Posesión con líneas de pase prohibidas', 'Juego de posesión 5v2 o 6v3 donde se prohíbe el pase atrás o el pase lateral según la zona. Obliga a buscar siempre la línea de pase progresiva.', '20 minutos', 'Desarrolla verticalidad y visión de pase progresivo bajo presión', 'field_positions', 'tactico'),
('Transición 4v4 con portero', 'Dos equipos de 4 jugadores más portero en medio campo. Tras robo, ataque inmediato al arco contrario. La velocidad de transición es el objetivo principal.', '4 series de 6 minutos', 'Automatiza cambio de rol defensa-ataque y mejora velocidad de transición', 'field_transition', 'tactico'),
('Pérdida y presión inmediata (6 segundos)', 'Ejercicio de posesión donde el equipo que pierde el balón tiene 6 segundos para recuperarlo. Basado en el principio de Gegenpressing (Klopp/Rangnick). Si no lo recupera, se reinicia.', '20 minutos', 'Desarrolla respuesta agresiva e inmediata ante la pérdida del balón', 'field_press', 'tactico'),
('Construcción con superioridad atrás (GK+3 vs 2)', 'El equipo en posesión sale desde el portero con tres defensas contra dos presionadores. Obliga a encontrar soluciones de circulación y progresión de forma organizada.', '20 minutos', 'Mejora construcción desde atrás y confianza de la línea defensiva con balón', 'field_buildup', 'tactico'),
('Timing en córner atacante', 'Práctica específica de córners ofensivos: señales de movimiento, bloques, arrastres y llegadas a zona de remate. Se trabajan 4-5 variantes codificadas.', '15 minutos (series de repeticiones)', 'Incrementa efectividad en jugadas de estrategia ofensiva y goles a balón parado', 'field_corner', 'tactico'),
('Cobertura y vigilancia defensiva', 'Ejercicio defensivo 4v4 en espacio cerrado donde se trabajan las posiciones de cobertura (detrás del compañero) y vigilancia (orientado para ver balón y rival simultáneamente).', '20 minutos', 'Solidez defensiva colectiva y comunicación entre líneas', 'field_defensive', 'tactico'),

-- resistencia (20)
('Intervalos de alta intensidad', 'Sprints de 30 segundos alternados con 30 segundos de trote.', '10-12 repeticiones', 'Mejora capacidad aeróbica y recuperación entre esfuerzos', 'sprint', 'resistencia'),
('Fartlek con balón', 'Cambios de ritmo conduciendo el balón en diferentes intensidades.', '20-25 minutos', 'Combina resistencia con habilidad técnica', 'run', 'resistencia'),
('Circuito de estaciones', 'Rotación por diferentes ejercicios: sprints, saltos, conducción, tiro.', '25-30 minutos', 'Resistencia muscular y cardiovascular específica', 'squat_jump', 'resistencia'),
('Partido reducido continuo', 'Partido en espacio reducido sin paradas prolongadas.', '20 minutos', 'Resistencia en situación real de juego', 'field_ssg', 'resistencia'),
('Carreras en escalera (Yoyo Test)', 'Carreras de ida y vuelta con incremento progresivo de velocidad.', '15-20 minutos', 'Evalúa y mejora resistencia anaeróbica láctica', 'sprint', 'resistencia'),
('Cambios de ritmo en campo completo', 'Sprint diagonal, trote lateral, sprint frontal en secuencia continua.', '8-10 repeticiones', 'Simula esfuerzos variables del partido real', 'run', 'resistencia'),
('Carrera continua 70-75% FCmax', 'Trote sostenido a ritmo moderado para base aeróbica.', '30-40 minutos', 'Desarrolla capacidad aeróbica de fondo', 'run', 'resistencia'),
('Series de 400m', 'Carreras de 400 metros a ritmo alto con recuperación activa.', '6-8 repeticiones', 'Potencia resistencia específica de medio fondo', 'sprint', 'resistencia'),
('Juego reducido con zonas', 'Partido con restricción de que jugadores deben cambiar de zona.', '4 series de 5 minutos', 'Resistencia con alta demanda cognitiva', 'field_ssg', 'resistencia'),
('Tabata de ejercicios mixtos', '20 segundos trabajo intenso, 10 segundos descanso con burpees, sprints, etc.', '8 rounds (4 minutos)', 'Máxima mejora de VO2max en corto tiempo', 'squat_jump', 'resistencia'),
('Recuperaciones activas post-sprint', 'Sprint máximo seguido de trote suave inmediato para recuperación.', '10-12 repeticiones', 'Mejora capacidad de recuperación durante el partido', 'sprint', 'resistencia'),
('Entrenamiento en umbrales', 'Carreras a ritmo de umbral anaeróbico mantenido.', '3-4 series de 8-10 minutos', 'Aumenta umbral láctico y resistencia a alta intensidad', 'run', 'resistencia'),
('Protocolo intermitente 10-10 (Bangsbo)', 'Método científico validado por Jens Bangsbo (Univ. Copenhague): 10 segundos de sprint al 100% seguidos de 10 segundos de trote suave. Optimiza la resíntesis de fosfocreatina y la remoción de lactato específica del fútbol.', '3 series de 12 repeticiones con 3 min descanso', 'Replica con exactitud la demanda metabólica del partido real y mejora recuperación entre sprints', 'sprint', 'resistencia'),
('Resistencia intermitente con balón 4 m/s', 'Protocolo de Kirka Athletic: conducción técnica del balón a velocidad controlada de 4 m/s en circuito de 40 metros. Estructura 10×10 con 12 repeticiones por serie. Volumen total por sesión: 1440 metros. Integra habilidad técnica con demanda cardiovascular.', '3 series de 12 reps (40m c/u) con 90s recuperación', 'Resistencia específica con balón que replica esfuerzos reales del partido', 'run', 'resistencia'),
('Método 30-15 IFT (Buchheit)', 'Intermittent Fitness Test de Martin Buchheit: 30 segundos de carrera con velocidad incremental cada ciclo, 15 segundos de recuperación pasiva. Permite calcular la Velocidad Máxima Aeróbica (VMA) y prescribir intensidades individualizadas.', 'Hasta el agotamiento voluntario (15-25 minutos)', 'Evaluación y desarrollo preciso de la capacidad aeróbica intermitente específica del fútbol', 'sprint', 'resistencia'),
('Series de 200m con recuperación técnica', 'Sprint de 200 metros al 90-95% seguido de trote de recuperación de 200 metros con conducción de balón. Combina estímulo anaeróbico con trabajo técnico en fatiga.', '6-8 repeticiones (descanso entre series: 2 min)', 'Mejora resistencia anaeróbica y mantenimiento técnico en fatiga', 'sprint', 'resistencia'),
('Hill Sprints (sprints en cuesta)', 'Sprints explosivos de 20-30 metros en pendiente del 8-12%. La inclinación reduce el impacto en articulaciones y aumenta la demanda muscular, especialmente de glúteos e isquiotibiales. Método utilizado por Adolfo Madrid (AM Health & Performance).', '8-10 repeticiones con 90 segundos recuperación', 'Desarrolla potencia-resistencia con bajo impacto articular y activación máxima de cadena posterior', 'sprint', 'resistencia'),
('Aerobic Power Interval (API)', 'Método noruego de alta intensidad: 4 minutos al 90-95% FCmax seguidos de 3 minutos al 65-70% FCmax. Protocolo 4×4 que maximiza el tiempo en zona de VO2max con recuperación activa.', '4 series alternadas (28 minutos total)', 'Mayor mejora documentada de VO2max en futbolistas en 8 semanas', 'run', 'resistencia'),
('Circuito 5×5 integrado', 'Bloque de 5 minutos de Small-Sided Game (partido reducido) + 5 minutos de trabajo físico específico (sprints, agilidad, pliometría). Se alternan bloques sin descanso entre ellos. Basado en metodología de Grupo Ekipo.', '4 bloques (40 minutos total)', 'Resistencia específica combinando demanda física y cognitiva en un estímulo continuo', 'field_ssg', 'resistencia'),
('Umbral anaeróbico con cambios de dirección', 'Carrera al 80-85% FCmax con cambios de dirección de 45° y 90° cada 40 metros. Mantiene la intensidad cerca del umbral anaeróbico incorporando el patrón de movimiento real del fútbol.', '3-4 series de 8 minutos con 3 min recuperación', 'Aumenta umbral láctico replicando el patrón locomotor real del partido', 'run', 'resistencia'),

-- pliometria (11)
('Saltos continuos sobre vallas bajas (Hurdles)', 'Saltos biapodales continuos sobre serie de 8-10 vallas bajas (30-40 cm) con mínimo tiempo de contacto en suelo. La clave es la reactividad y rigidez del tobillo. Herramienta analizada por Armando Altamirano (Living4Football).', '4 series de 8-10 vallas con 2 min descanso', 'Mejora la elasticidad del complejo tobillo-tendón y la reactividad para cambios de ritmo', 'hurdle_jump', 'pliometria'),
('Depth Jump', 'Caída desde cajón (60-80 cm) → amortiguación inmediata con mínimo tiempo de contacto → salto vertical máximo. Trabaja el ciclo estiramiento-acortamiento (CEA) en su máxima expresión. Fundamento de Carmelo Bosco.', '4 series de 6 repeticiones con 3 min descanso', 'Máximo desarrollo del ciclo estiramiento-acortamiento y potencia explosiva de salto', 'depth_jump', 'pliometria'),
('Saltos laterales alternos con vallas', 'Saltos laterales alternando lados sobre vallas de 40-50 cm. Replica el patrón lateral de cambio de dirección. Progresión: velocidad → reactividad → vallas más altas.', '3 series de 10 saltos (5 cada lado) con 90s descanso', 'Potencia lateral y agilidad reactiva para cambios de dirección', 'jump_lateral', 'pliometria'),
('Triple salto horizontal', 'Secuencia: salto desde dos piernas → aterrizaje una pierna → salto → aterrizaje otra pierna → salto de longitud. Trabaja la transferencia de energía y el equilibrio dinámico en máxima potencia.', '4 series de 5 repeticiones con 2 min descanso', 'Potencia horizontal explosiva y coordinación de transferencia de energía entre apoyos', 'triple_jump', 'pliometria'),
('Drop Jump + Sprint de 10m', 'Caída desde cajón → contacto mínimo → sprint explosivo de 10 metros. Conecta la potencia pliométrica con la aceleración específica del sprint en fútbol.', '5 series de 4 repeticiones con 2 min descanso', 'Transferencia directa de potencia pliométrica a la aceleración inicial de sprint', 'depth_jump', 'pliometria'),
('Skipping de alta frecuencia', 'Carrera en el sitio con elevación de rodillas al máximo y máxima frecuencia de pisada. Trabaja la velocidad de movimiento de piernas y la coordinación neuromuscular.', '4 series de 20 segundos con 40s descanso', 'Aumenta la frecuencia de zancada y la velocidad de movimiento de piernas', 'skipping', 'pliometria'),
('Bounds alternos (zancadas explosivas)', 'Zancadas horizontales máximas alternando piernas, buscando la mayor distancia por impulsión. Cada aterrizaje se convierte inmediatamente en el siguiente impulso. Analizado por Armando Altamirano para fase de vuelo.', '4 series de 20 metros con 2 min descanso', 'Potencia de impulsión horizontal y longitud de zancada en sprint', 'bounds', 'pliometria'),
('CMJ — Counter Movement Jump', 'Salto vertical con contra-movimiento: semiflexión rápida de rodillas seguida de salto máximo. Herramienta de evaluación y entrenamiento de potencia de Bosco (1983). Se puede medir con app o plataforma de fuerza.', '3 series de 8 saltos con 2 min descanso', 'Desarrolla y evalúa la potencia muscular de piernas y el aprovechamiento del CEA', 'jump_vertical', 'pliometria'),
('Reactive Agility Drill con señal visual', 'El atleta parte en posición de espera. Al recibir señal visual (luz, gesto del entrenador) debe reaccionar y cambiar de dirección hacia el punto indicado. Integra tiempo de reacción con potencia explosiva.', '4 series de 6 repeticiones con 90s descanso', 'Mejora el tiempo de reacción y la agilidad reactiva ante estímulos imprevistos del juego', 'agility_ladder', 'pliometria'),
('Saltos en escalera de agilidad', 'Progresiones en escalera de coordinación: dos pies dentro-fuera, pies alternos, lateral shuffle, Ickey shuffle. Progresión de velocidad en cada serie.', '4 series de 3 longitudes de escalera con 60s descanso', 'Coordinación de pies, velocidad de movimiento y patrones de carrera específicos del fútbol', 'agility_ladder', 'pliometria'),
('Salto en largo desde parado', 'Impulso biapodal buscando la máxima distancia horizontal desde posición estática. Mide y entrena la potencia explosiva horizontal sin componente de carrera previa.', '4 series de 6 saltos con 90s descanso', 'Potencia explosiva horizontal y fuerza de impulsión para aceleración inicial', 'bounds', 'pliometria'),

-- prevencion (11)
('Entrenamiento con BOSU — Propiocepción', 'Ejercicios sobre plataforma BOSU (semiesfera inestable) para activar el sistema neuromuscular del tobillo y rodilla: equilibrio estático, sentadilla, lanzamientos de balón. Validado por Forum Sport para prevención de osteopatía de pubis.', '3 series de 12-15 reps por ejercicio', 'Mejora la propiocepción de tobillo y rodilla, reduciendo el riesgo de esguinces y lesiones articulares', 'balance_single', 'prevencion'),
('Nordic Hamstring Curl', 'De rodillas con los pies sujetos, descender el cuerpo hacia adelante usando solo los isquiotibiales como freno. Ejercicio excéntrico de máxima evidencia científica para prevención de distensiones musculares (revisión sistemática Petersen, 2011).', '3 series de 6-8 repeticiones con 2 min descanso', 'Reduce hasta un 51% la incidencia de lesiones de isquiotibiales (nivel de evidencia A)', 'nordic_curl', 'prevencion'),
('Estiramientos dinámicos pre-partido', 'Secuencia de estiramientos dinámicos específicos del fútbol: balanceos de pierna frontal y lateral, skipping, shuffles, rotaciones de cadera, lunges con rotación. Reemplaza los estiramientos estáticos en el calentamiento según literatura actual.', '10-12 minutos antes del entrenamiento o partido', 'Prepara el sistema neuromuscular sin inhibir la fuerza, reduciendo el riesgo de lesión en los primeros minutos', 'stretch_dynamic', 'prevencion'),
('Activación glúteo medio con banda', 'Con banda elástica en tobillos o rodillas: marcha lateral, clamshells, monster walk, fire hydrant. Activa el glúteo medio para estabilizar cadera y rodilla en los apoyos.', '3 series de 15 reps por ejercicio con banda', 'Previene el valgo de rodilla, la tendinopatía rotuliana y las lesiones de cadera', 'band_walk', 'prevencion'),
('Equilibrio monopodal con perturbación', 'Equilibrio sobre una pierna con ojos abiertos (1 min) y cerrados (30s). Añadir perturbaciones: recibir/lanzar balón, compañero empuja suavemente. Progression: base firme → BOSU → ojos cerrados.', '3 series de 60 segundos por pierna', 'Sistema propioceptivo del tobillo y rodilla para prevención de esguinces y mejora del control motor', 'balance_single', 'prevencion'),
('Fortalecimiento de aductores (prevención pubalgia)', 'Ejercicios específicos de aductores: Copenhagen Adductor Exercise (pierna apoyada en banco, elevar cadera desde el suelo), aducción con polea o máquina. Específico para reducir pubalgias en futbolistas (Hölmich, 1999).', '3 series de 10-12 reps con 90s descanso', 'Reduce significativamente la incidencia de pubalgia, la lesión crónica más prevalente en futbolistas', 'copenhagen', 'prevencion'),
('Foam Rolling — Protocolo de recuperación', 'Automasaje con rodillo de espuma sobre: cuádriceps (2 min), isquiotibiales (2 min), banda iliotibial (1 min por lado), gemelos (1 min), glúteos (1 min). Preferiblemente post-entrenamiento. Adolfo Madrid incluye esto en el entrenamiento invisible.', '10-15 minutos post-entrenamiento', 'Reducción de DOMS (dolor muscular tardío), mejora de la recuperación y mantenimiento de rango de movimiento', 'foam_roll', 'prevencion'),
('Movilidad de cadera funcional', 'Secuencia de movilidad de cadera: 90/90 stretch, pigeon pose dinámico, rotación interna y externa de cadera en suelo, world''s greatest stretch. Mejora el rango de movimiento necesario para los gestos técnicos del fútbol.', '10-12 minutos (2 min por ejercicio)', 'Previene lesiones de cadera e ingle, mejora la fluidez de movimiento en cambios de dirección', 'hip_mobility', 'prevencion'),
('Activación del pie y tobillo', 'Ejercicios específicos: elevaciones de talón con una pierna, escritura del abecedario con el pie, caminar sobre talones y puntillas, recogida de objetos con los dedos del pie. Activa la musculatura intrínseca del pie.', '2 series de 15-20 reps por ejercicio', 'Previene esguinces de tobillo y la fascitis plantar, mejora la estabilidad dinámica del pie', 'foot_activation', 'prevencion'),
('Calentamiento FIFA 11+', 'Protocolo completo de prevención de lesiones desarrollado por el Centro de Evaluación e Investigación de la FIFA (F-MARC). 3 partes: (1) Carrera con ejercicios (8 min), (2) Fuerza, pliometría y equilibrio (10 min), (3) Carrera con sprints (2 min). Se debe realizar al inicio de cada entrenamiento.', '20 minutos completos al inicio del entrenamiento', 'Reduce hasta un 50% el riesgo de lesión general y un 71% las lesiones graves según estudios en 2000+ jugadores', 'warmup_run', 'prevencion'),
('Crioterapia y recuperación post-esfuerzo', 'Protocolo de recuperación biológica de élite (Adolfo Madrid / AM Health & Performance): baño de contraste (1 min frío 12°C + 1 min caliente, 6 ciclos) o inmersión en agua fría 12-15°C durante 10-12 min. Alternativa: crioterapia localizada en zonas de alta carga.', '10-15 minutos post-partido o entrenamiento intenso', 'Acelera la eliminación de lactato y reduce la inflamación para recuperación más rápida entre sesiones', 'ice_bath', 'prevencion');

-- ══════════════════════════════════════════════════════════
-- Seed injury_categories
-- ══════════════════════════════════════════════════════════
INSERT INTO injury_categories (slug, name, icon, color) VALUES
('esguinces', 'Esguinces', 'ankle', 'from-red-500 to-orange-500'),
('sobrecargas', 'Sobrecargas musculares', 'muscle', 'from-yellow-500 to-orange-500'),
('roturas', 'Roturas musculares', 'flame', 'from-red-600 to-pink-600'),
('lesiones-rodilla', 'Lesiones de rodilla', 'knee', 'from-blue-500 to-cyan-500'),
('tendinosas', 'Lesiones tendinosas', 'tendon', 'from-green-500 to-emerald-500'),
('oseas', 'Lesiones óseas', 'bone', 'from-gray-500 to-slate-600'),
('otras', 'Otras lesiones', 'first-aid', 'from-purple-500 to-pink-500');

-- ══════════════════════════════════════════════════════════
-- Seed injuries
-- ══════════════════════════════════════════════════════════
INSERT INTO injuries (slug, category_id, name, what_is, how_it_happens, treatment, prevention) VALUES
-- esguinces
('esguince-tobillo', (SELECT id FROM injury_categories WHERE slug='esguinces'), 'Esguince de tobillo', 'Lesión en los ligamentos del tobillo causada por una torsión o estiramiento excesivo.', 'Al apoyar mal el pie, en cambios bruscos de dirección, saltos o contacto con otro jugador.', 'Reposo, hielo, compresión y elevación (RICE). Fisioterapia progresiva y vendaje funcional.', 'Fortalecimiento del tobillo, ejercicios propioceptivos, buen calentamiento y calzado adecuado.'),
('esguince-rodilla', (SELECT id FROM injury_categories WHERE slug='esguinces'), 'Esguince de rodilla', 'Daño en los ligamentos de la rodilla por movimientos forzados o impactos.', 'Giros bruscos, frenadas repentinas o choques durante el juego.', 'Reposo, inmovilización parcial, fisioterapia y en casos graves intervención médica.', 'Trabajo de fuerza en piernas, estabilidad articular y técnica correcta de movimiento.'),
('esguince-lcm', (SELECT id FROM injury_categories WHERE slug='esguinces'), 'Esguince de ligamento colateral medial', 'Lesión del ligamento lateral interno de la rodilla.', 'Impacto lateral en la rodilla o movimientos de valgo forzado.', 'Inmovilización con ortesis, fisioterapia y fortalecimiento progresivo.', 'Trabajo de estabilidad de rodilla y fortalecimiento de aductores.'),
('esguince-muneca', (SELECT id FROM injury_categories WHERE slug='esguinces'), 'Esguince de muñeca', 'Lesión de los ligamentos de la muñeca, común en porteros.', 'Caídas apoyando la mano o atajadas forzadas.', 'Inmovilización temporal, hielo y fisioterapia.', 'Fortalecimiento de muñeca y técnica correcta de caída.'),
-- sobrecargas
('sobrecarga-gemelos', (SELECT id FROM injury_categories WHERE slug='sobrecargas'), 'Sobrecarga de gemelos', 'Fatiga excesiva del músculo del gemelo sin rotura de fibras.', 'Exceso de carga, falta de descanso o mala recuperación entre entrenamientos.', 'Descanso activo, masaje deportivo, estiramientos suaves y control de cargas.', 'Planificación adecuada de entrenamientos y buena hidratación.'),
('sobrecarga-isquiotibiales', (SELECT id FROM injury_categories WHERE slug='sobrecargas'), 'Sobrecarga de isquiotibiales', 'Acumulación de fatiga en los músculos posteriores del muslo.', 'Entrenamientos intensos, sprints repetidos o falta de calentamiento.', 'Reducción de carga, fisioterapia y trabajo excéntrico progresivo.', 'Fortalecimiento excéntrico y control del volumen de entrenamiento.'),
('sobrecarga-aductores', (SELECT id FROM injury_categories WHERE slug='sobrecargas'), 'Sobrecarga de aductores', 'Fatiga muscular en la zona de la ingle sin rotura.', 'Cambios de dirección repetidos y movimientos laterales constantes.', 'Reposo relativo, masaje profundo y fortalecimiento gradual.', 'Trabajo específico de aductores y buenos estiramientos.'),
('sobrecarga-cuadriceps', (SELECT id FROM injury_categories WHERE slug='sobrecargas'), 'Sobrecarga de cuádriceps', 'Tensión excesiva en la musculatura anterior del muslo.', 'Carreras intensas, saltos repetidos o entrenamiento sin recuperación.', 'Descanso activo, crioterapia y masaje deportivo.', 'Dosificación adecuada de cargas y estiramientos post-entrenamiento.'),
('sobrecarga-lumbar', (SELECT id FROM injury_categories WHERE slug='sobrecargas'), 'Sobrecarga lumbar', 'Tensión en la musculatura de la zona baja de la espalda.', 'Malas posturas, cabezazos repetidos o falta de fortalecimiento de core.', 'Fisioterapia, estiramientos y fortalecimiento del core.', 'Trabajo de core, técnica correcta y control postural.'),
-- roturas
('rotura-isquiotibiales', (SELECT id FROM injury_categories WHERE slug='roturas'), 'Rotura fibrilar de isquiotibiales', 'Rotura parcial de fibras musculares en la parte posterior del muslo.', 'Sprint explosivo o aceleración brusca sin preparación adecuada.', 'Reposo, fisioterapia, readaptación progresiva y control médico.', 'Trabajo excéntrico, calentamiento completo y evitar sobrecargas.'),
('rotura-cuadriceps', (SELECT id FROM injury_categories WHERE slug='roturas'), 'Rotura de cuádriceps', 'Desgarro muscular en la parte frontal del muslo.', 'Golpeo fuerte del balón o cambios bruscos de ritmo.', 'Reposo, hielo, fisioterapia y fortalecimiento progresivo.', 'Buena preparación muscular y gestión de la fatiga.'),
('rotura-gemelos', (SELECT id FROM injury_categories WHERE slug='roturas'), 'Rotura de gemelos', 'Desgarro de las fibras del músculo gemelar o sóleo.', 'Aceleración súbita o salto sin calentamiento adecuado.', 'Reposo, elevación, compresión y rehabilitación progresiva.', 'Calentamiento específico de gemelos y buenos estiramientos.'),
('rotura-aductores', (SELECT id FROM injury_categories WHERE slug='roturas'), 'Rotura de aductores', 'Desgarro muscular en la zona de la ingle.', 'Apertura excesiva de piernas o movimiento lateral forzado.', 'Reposo absoluto inicial, fisioterapia y fortalecimiento gradual.', 'Fortalecimiento progresivo de aductores y flexibilidad.'),
('rotura-recto-anterior', (SELECT id FROM injury_categories WHERE slug='roturas'), 'Rotura del recto anterior', 'Desgarro del músculo recto anterior del cuádriceps.', 'Disparo potente del balón con estiramiento excesivo.', 'Reposo, crioterapia y readaptación específica.', 'Fortalecimiento del cuádriceps y técnica de golpeo correcta.'),
-- lesiones-rodilla
('lca', (SELECT id FROM injury_categories WHERE slug='lesiones-rodilla'), 'Lesión del ligamento cruzado anterior (LCA)', 'Rotura o estiramiento grave del ligamento cruzado anterior.', 'Giros bruscos, aterrizajes mal ejecutados o contacto fuerte.', 'Cirugía en muchos casos y rehabilitación prolongada.', 'Trabajo neuromuscular, estabilidad y técnica de salto correcta.'),
('meniscopatia', (SELECT id FROM injury_categories WHERE slug='lesiones-rodilla'), 'Meniscopatía', 'Lesión del menisco de la rodilla.', 'Movimientos repetidos de giro o impacto directo.', 'Fisioterapia o cirugía según gravedad.', 'Fortalecer musculatura de soporte y evitar sobrecargas.'),
('lcp', (SELECT id FROM injury_categories WHERE slug='lesiones-rodilla'), 'Lesión del ligamento cruzado posterior (LCP)', 'Daño en el ligamento cruzado posterior de la rodilla.', 'Golpe directo en la parte frontal de la rodilla flexionada.', 'Conservador con fisioterapia o cirugía en casos graves.', 'Protección adecuada y fortalecimiento de musculatura.'),
('condromalacia', (SELECT id FROM injury_categories WHERE slug='lesiones-rodilla'), 'Condromalacia rotuliana', 'Desgaste del cartílago de la rótula.', 'Sobrecarga repetitiva, desalineación rotuliana o debilidad muscular.', 'Fisioterapia, fortalecimiento de cuádriceps y control de carga.', 'Técnica correcta de carrera y fortalecimiento equilibrado.'),
('sindrome-cintilla', (SELECT id FROM injury_categories WHERE slug='lesiones-rodilla'), 'Síndrome de la cintilla iliotibial', 'Inflamación de la banda iliotibial en su inserción lateral de rodilla.', 'Carreras prolongadas, especialmente en superficies inclinadas.', 'Reposo, fisioterapia, estiramientos y liberación miofascial.', 'Fortalecimiento de glúteos y estiramiento de cintilla.'),
-- tendinosas
('tendinitis-rotuliana', (SELECT id FROM injury_categories WHERE slug='tendinosas'), 'Tendinitis rotuliana', 'Inflamación del tendón rotuliano.', 'Saltos repetidos y sobrecarga del aparato extensor.', 'Reposo, fisioterapia, ejercicios excéntricos.', 'Control de carga y fortalecimiento progresivo.'),
('tendinitis-aquilea', (SELECT id FROM injury_categories WHERE slug='tendinosas'), 'Tendinitis aquílea', 'Inflamación del tendón de Aquiles.', 'Exceso de carrera, calzado inadecuado o mala pisada.', 'Reposo, hielo, fisioterapia y estiramientos.', 'Trabajo de gemelos y control de impacto.'),
('tendinopatia-aductores', (SELECT id FROM injury_categories WHERE slug='tendinosas'), 'Tendinopatía de aductores', 'Inflamación de los tendones de los músculos aductores.', 'Movimientos laterales repetitivos y sobrecarga.', 'Fisioterapia, ejercicios excéntricos y ondas de choque.', 'Fortalecimiento progresivo de aductores.'),
('tendinitis-cudriceps', (SELECT id FROM injury_categories WHERE slug='tendinosas'), 'Tendinitis del cuádriceps', 'Inflamación del tendón del cuádriceps por encima de la rótula.', 'Saltos, cambios de ritmo y golpeos repetidos.', 'Reposo relativo, fisioterapia y trabajo excéntrico.', 'Control de volumen de entrenamiento y flexibilidad.'),
('tendinitis-peroneos', (SELECT id FROM injury_categories WHERE slug='tendinosas'), 'Tendinitis de peroneos', 'Inflamación de los tendones peroneos en el tobillo.', 'Esguinces previos, sobrecarga o mala pisada.', 'Reposo, fisioterapia y trabajo propioceptivo.', 'Fortalecimiento de peroneos y estabilidad de tobillo.'),
-- oseas
('fractura-estres', (SELECT id FROM injury_categories WHERE slug='oseas'), 'Fractura por estrés', 'Microfracturas óseas por sobreuso.', 'Carga repetitiva sin recuperación adecuada.', 'Reposo prolongado y control médico.', 'Buena planificación de cargas y nutrición adecuada.'),
('periostitis', (SELECT id FROM injury_categories WHERE slug='oseas'), 'Periostitis tibial', 'Inflamación del periostio (membrana que cubre el hueso) de la tibia.', 'Impactos repetidos al correr en superficies duras.', 'Reposo, hielo, antiinflamatorios y fisioterapia.', 'Calzado adecuado, superficies apropiadas y progresión gradual.'),
('fractura-metacarpiano', (SELECT id FROM injury_categories WHERE slug='oseas'), 'Fractura de metacarpiano', 'Rotura de los huesos de la mano, común en porteros.', 'Impacto directo al atajar o golpear el balón.', 'Inmovilización o cirugía según gravedad.', 'Técnica correcta de atajada y protección adecuada.'),
('fractura-clavicula', (SELECT id FROM injury_categories WHERE slug='oseas'), 'Fractura de clavícula', 'Rotura del hueso de la clavícula.', 'Caídas sobre el hombro o contacto fuerte.', 'Inmovilización con cabestrillo o cirugía si es desplazada.', 'Técnica correcta de caída y fortalecimiento del tren superior.'),
('osteitis-pubis', (SELECT id FROM injury_categories WHERE slug='oseas'), 'Osteítis de pubis', 'Inflamación de la sínfisis púbica.', 'Sobrecarga repetitiva de aductores y movimientos de corte.', 'Reposo prolongado, fisioterapia y fortalecimiento del core.', 'Fortalecimiento de aductores, core y control de cargas.'),
-- otras
('fascitis-plantar', (SELECT id FROM injury_categories WHERE slug='otras'), 'Fascitis plantar', 'Inflamación de la fascia plantar del pie.', 'Sobrecarga repetitiva, calzado inadecuado o mala pisada.', 'Estiramientos específicos, fisioterapia y plantillas ortopédicas.', 'Calzado apropiado, estiramientos y fortalecimiento de pie.'),
('pubalgia', (SELECT id FROM injury_categories WHERE slug='otras'), 'Pubalgia', 'Dolor en la zona del pubis y la ingle por sobrecarga.', 'Desequilibrios musculares y sobrecarga de aductores.', 'Fisioterapia, fortalecimiento del core y en casos graves cirugía.', 'Trabajo equilibrado de abdominales y aductores.'),
('hernia-deportista', (SELECT id FROM injury_categories WHERE slug='otras'), 'Hernia del deportista', 'Debilidad de la pared abdominal en zona inguinal.', 'Movimientos explosivos y giros repetidos.', 'Cirugía en la mayoría de casos y rehabilitación.', 'Fortalecimiento del core y técnica correcta.'),
('conmocion-cerebral', (SELECT id FROM injury_categories WHERE slug='otras'), 'Conmoción cerebral', 'Lesión cerebral traumática leve por impacto.', 'Choque de cabezas, golpe con el suelo o balón fuerte.', 'Reposo absoluto cognitivo y físico, evaluación médica.', 'Técnica correcta de cabeceo y evaluación ante cualquier síntoma.'),
('luxacion-hombro', (SELECT id FROM injury_categories WHERE slug='otras'), 'Luxación de hombro', 'Desplazamiento de la cabeza del húmero fuera de la cavidad.', 'Caídas sobre el brazo extendido o impactos directos.', 'Reducción médica, inmovilización y fisioterapia.', 'Fortalecimiento del manguito rotador.'),
('contusion-muscular', (SELECT id FROM injury_categories WHERE slug='otras'), 'Contusión muscular', 'Golpe directo en el músculo que causa hematoma.', 'Impacto con otro jugador, rodillazo o entrada fuerte.', 'Hielo inmediato, compresión y drenaje si es necesario.', 'Protecciones y evitar contactos innecesarios.');
